### ISSUE TITLE
NoSuchMethod exception

### ISSUE THREAD

**Issue by foscocorazza** [GetStream/stream-java#52]
On Android project, this copy-pasted code from examples is not working:

```
 try {
   Client client = Client.builder(<ApiKey>, <ApiSecret>).build();
   FlatFeed chris = client.flatFeed("user", "chris");
   chris.addActivity(Activity.builder()
                    .actor("chris")
                    .verb("add")
                    .object("picture:10")
                    .foreignID("picture:10")
                    .extraField("message", "Beautiful bird!")
                    .build());

} catch (MalformedURLException e) {
} catch (StreamException e) {}
```

`chris.addActivity()` throws this exception:

```
    java.lang.NoSuchMethodError: No static method encodeBase64URLSafeString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at com.auth0.jwt.JWTCreator.sign(JWTCreator.java:330)
        at com.auth0.jwt.JWTCreator.access$100(JWTCreator.java:24)
        at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:311)
        at io.getstream.core.utils.Auth.buildBackendToken(Auth.java:135)
        at io.getstream.core.utils.Auth.buildBackendToken(Auth.java:123)
        at io.getstream.core.utils.Auth.buildFeedToken(Auth.java:60)
        at io.getstream.client.Client.addActivity(Client.java:249)
        at io.getstream.client.Feed.addActivity(Feed.java:56)
```

**Comment by Nekuromento** [comment]
`Client` class is intended for server use only. You should use `CloudClient` version for android development (https://getstream.github.io/stream-java/io/getstream/cloud/CloudClient.html)

The code would look like this:
```java
 try {
   CloudClient client = CloudClient.builder(<ApiKey>, <Token>).build();
   CloudFlatFeed chris = client.flatFeed("user", "chris");
   chris.addActivity(Activity.builder()
                    .actor("chris")
                    .verb("add")
                    .object("picture:10")
                    .foreignID("picture:10")
                    .extraField("message", "Beautiful bird!")
                    .build());

} catch (MalformedURLException e) {
} catch (StreamException e) {}
```
